- id: https://doi.org/10.3389/fphys.2019.01321
  type: paper
  description: Describing the development of a sepsis model and the physiologic response within the BioGears framework.
  date: 2019-10-1
  image: https://www.frontiersin.org/files/Articles/470546/fphys-10-01321-HTML/image_m/fphys-10-01321-g003.jpg
  buttons:
    - type: source
      text: Manuscript Source
      link: https://www.frontiersin.org/journals/physiology/articles/10.3389/fphys.2019.01321/full
    - type: website
      link: https://github.com/BioGearsEngine/core
  tags:
    - open science
    - Sepsis 
    - BioGears
  repo: BioGearsEngine/core
